# -*- coding: utf-8 -*-
"""code 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJa4Zz4Kt2aozC4e264dlQ3REUDTecaN
"""

pip install transformers touch

from transformers import pipeline
generator = pipeline(
    "text-generator",
    model="gpt2"
)
promt ="artificial intelligence in finance will"
result=generator(promt,max_length=50,num_return_sequences=1)
print("AI Generated text:")
print(result[0]['generated_text'])