# -*- coding: utf-8 -*-
"""code 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qtz6WCY25zFwy1SJpBj0zAnKWt8somdK
"""

!pip install  sentence-transformers

from transformers import pipeline

# Load text generation pipeline with GPT-2
generator = pipeline("text-generation", model="gpt2")

prompt = "Artificial intelegence"

# Generate text
result = generator(prompt, max_length=50, num_return_sequences=1)

print("AI Generated Text:")
print(result[0]['generated_text'])