# -*- coding: utf-8 -*-
"""gen Ai 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vSmd3PO9ePvwIrZfd4hOlADoOLXoX_cq
"""

!pip install sentence_Transformers

from sentence_transformers import SentenceTransformer, util

#load the model
model = SentenceTransformer('all-MiniLM-L6-V2')

#Take input from user
text1 = input("Enter Text 1: ")
text2 = input("Enter Text 2: ")

#convert text to embeddings
embedding1 = model.encode(text1)
embedding2 = model.encode(text2)

#calculate similarity
similarity = util.cos_sim(embedding1,embedding2)

#show result
print("\nsimilarity score:", round(float(similarity), 2))

if similarity > 0.75:
  print("similarity Level: High")
elif similarity > 0.4:
  print("similarity Level: medium")
else:
  print("similarity Level: Low")